# 验证 CocoaPods 本地 path 集成。
# 使用方式：
#   cd TestApp-CocoaPods
#   pod install
#   open FastPackageTestApp.xcworkspace
#
platform :ios, '14.0'
use_frameworks!

target 'FastPackageTestApp' do
  pod 'FastPackage', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
